### ISSUE TITLE
Unable to load kext manually

### ISSUE THREAD

**Issue by soham2008xyz** [usr-sse2/Black80211-Catalina#11]
Sohams-ZenBook:Black80211-Catalina sohambanerjee$ sudo kextutil Black80211.kext -r .
Kext with invalid signature (-67050) allowed: <OSKext 0x7feac4f2bd80 [0x7fff8637fcc0]> { URL = "file:///Users/sohambanerjee/Desktop/Black80211-Catalina/Black80211.kext/", ID = "net.rpeshkov.Black80211" }
Code Signing Failure: code signature is invalid
Disabling KextAudit: SIP is off
Invalid signature -67050 for kext <OSKext 0x7feac4f2bd80 [0x7fff8637fcc0]> { URL = "file:///Users/sohambanerjee/Desktop/Black80211-Catalina/Black80211.kext/", ID = "net.rpeshkov.Black80211" }
Sohams-ZenBook:Black80211-Catalina sohambanerjee$ sudo kextutil Black80211.kext -r .
Kext with invalid signature (-67050) allowed: <OSKext 0x7fd4a472bd80 [0x7fff8637fcc0]> { URL = "file:///Users/sohambanerjee/Desktop/Black80211-Catalina/Black80211.kext/", ID = "net.rpeshkov.Black80211" }
Code Signing Failure: code signature is invalid
Invalid signature -67050 for kext <OSKext 0x7fd4a472bd80 [0x7fff8637fcc0]> { URL = "file:///Users/sohambanerjee/Desktop/Black80211-Catalina/Black80211.kext/", ID = "net.rpeshkov.Black80211" }

**Comment by soham2008xyz** [comment]
I am able to load the kexts with OpenCore, but not manually once booted

**Comment by usr-sse2** [comment]
Disable System Integrity Protection to load unsigned kexts.

**Comment by igorkulman** [comment]
I have SIP disabled

```bash
❯ csrutil status
System Integrity Protection status: disabled.
```

and I still get

```
Kext with invalid signature (-67050) allowed: <OSKext 0x7fc4c251d460 [0x7fff89973cc0]> { URL = "file:///Users/igorkulman/Downloads/alpha1.1/Black80211.kext/", ID = "net.rpeshkov.Black80211" }
Code Signing Failure: code signature is invalid
Invalid signature -67050 for kext <OSKext 0x7fc4c251d460 [0x7fff89973cc0]> { URL = "file:///Users/igorkulman/Downloads/alpha1.1/Black80211.kext/", ID = "net.rpeshkov.Black80211" }
```

**Comment by nkngdev** [comment]
> I have SIP disabled
> 
> 
> 
> ```bash
> 
> ❯ csrutil status
> 
> System Integrity Protection status: disabled.
> 
> ```
> 
> 
> 
> and I still get
> 
> 
> 
> ```
> 
> Kext with invalid signature (-67050) allowed: <OSKext 0x7fc4c251d460 [0x7fff89973cc0]> { URL = "file:///Users/igorkulman/Downloads/alpha1.1/Black80211.kext/", ID = "net.rpeshkov.Black80211" }
> 
> Code Signing Failure: code signature is invalid
> 
> Invalid signature -67050 for kext <OSKext 0x7fc4c251d460 [0x7fff89973cc0]> { URL = "file:///Users/igorkulman/Downloads/alpha1.1/Black80211.kext/", ID = "net.rpeshkov.Black80211" }
> 
> ```

Disable Gatekeeper

**Comment by igorkulman** [comment]
> Disable Gatekeeper

Also disabled

```
❯ spctl --status
assessments disabled
```

**Comment by soham2008xyz** [comment]
SIP & Gatekeeper are both disabled

**Comment by Silfalion** [comment]
have the exact same issue, both SIP and Gatekeeper disabled as well. Would a debug version allow to by pass the signing maybe?

**Comment by usr-sse2** [comment]
I accidentally signed the kext for local running. I'll update the release with the unsigned kext.

**Comment by Silfalion** [comment]
Cool! Thank you.

**Comment by usr-sse2** [comment]
[unsigned.zip](https://github.com/usr-sse2/Black80211-Catalina/files/5021198/unsigned.zip)
@Silfalion @igorkulman @soham2008xyz Please check if it loads.

**Comment by soham2008xyz** [comment]
I was trying to load the kext after building locally. I realized I had signed the build as well. Will try loading the unsigned kext.

**Comment by igorkulman** [comment]
> [unsigned.zip](https://github.com/usr-sse2/Black80211-Catalina/files/5021198/unsigned.zip)
> @Silfalion @igorkulman @soham2008xyz Please check if it loads.

```
❯ sudo kextutil Black80211.kext -r .
Kext with invalid signature (-67062) allowed: <OSKext 0x7fd6d8f05960 [0x7fff8c077cc0]> { URL = "file:///Users/igorkulman/Downloads/unsigned/Black80211.kext/", ID = "net.rpeshkov.Black80211" }
Code Signing Failure: not code signed
Disabling KextAudit: SIP is off
```

**Comment by usr-sse2** [comment]
@igorkulman ...and what? did it load? it displayed that it's not signed and that it allowed it to load.

**Comment by igorkulman** [comment]
> @igorkulman ...and what? did it load? it displayed that it's not signed and that it allowed it to load.

`kexstat` says the kext is loaded but `itlwm` is not loaded and the adapter does not appear in the system.

**Comment by usr-sse2** [comment]
@igorkulman Oh, that part of README got outdated. During early development itlwm was Black80211's dependency, and so `kextutil` automatically loaded. Later I redesigned it to match on any wireless device, to allow future compatibility with itlwmx or possible other wireless drivers if someone makes them, and now itlwm should be loaded manually. I've updated the README.

**Comment by Silfalion** [comment]
lol it always bugged me itlwm wasn't added to be loaded. will try now.

**Comment by Silfalion** [comment]
it works marvels. Thank you. Have to add that itlwm wasn't working for me until I updated to OpenCore 0.6.0 earlier this morning. Black802-11 adds that it no longer appears as ethernet, right?

**Comment by igorkulman** [comment]
Now it loads, scans but it does not see my network (wp2 personal, works with heliport), just networks of my neighbors. Any idea why?

**Comment by usr-sse2** [comment]
@igorkulman which channel is your network on? Is that channel listed in supported channels in System Profiler?
There are scanning issues that I'm aware of, it often doesn't see my 5 GHz network on channel 149 but usually sees my 2.4 GHz network on channel 1.

**Comment by igorkulman** [comment]
> @igorkulman which channel is your network on? Is that channel listed in supported channels in System Profiler?
> There are scanning issues that I'm aware of, it often doesn't see my 5 GHz network on channel 149 but usually sees my 2.4 GHz network on channel 1.

I opened a separate issue https://github.com/usr-sse2/Black80211-Catalina/issues/15

**Comment by soham2008xyz** [comment]
The kext loading works now.
