### ISSUE TITLE
can only see 17 dbm wifi connection and after delete can't use normal heliport

### ISSUE THREAD

**Issue by ndhanh96** [usr-sse2/Black80211-Catalina#14]
it can only see 17 dbm wifi signal and after i delete it i can use heliport with itlwm in kext folder anymore.
i installed it in L/E and rebuild kext. after delete i can't use normal itlwm anymore.
![Screen Shot 2020-08-04 at 07 50 27](https://user-images.githubusercontent.com/8610547/89240755-3a653000-d627-11ea-8e4d-5e86ccfb870b.png)
probably it can't assign the ip.

**Comment by usr-sse2** [comment]
About the exclamation mark sign: it sometimes doesn't work, try disabling Wi-Fi from the menu and enabling it again. Check that you entered the correct password.
About heliport: this itlwm won't work with HeliPort, did you revert to the original one? What do you mean by 'can't use'? Are there any error messages, or what?

**Comment by ndhanh96** [comment]
after i delete your combo kext, i can't use the original anymore, the exclamation mark sign.
about yours kext it only shows far away wifi, it doesn't even show my home wifi network.

**Comment by usr-sse2** [comment]
Is the exclamation mark in HeliPort or in Apple AirPort menu item?
You can check which itlwm is loaded using IORegistryExplorer. If it has Black80211Device base class, it's my itlwm, and if it has IOEthernetController base class, then it's the original one.
![Screenshot 2020-08-04 at 14 57 52](https://user-images.githubusercontent.com/446776/89291282-f55eef00-d662-11ea-9239-6909c1d03d0c.png)

The second issue is known as #15.

**Comment by usr-sse2** [comment]
I found the reason of not showing networks. You can try to set your home network to channel 1 until I release a fix.

**Comment by usr-sse2** [comment]
@ndhanh96 Please try the version attached at #15. Changing to channel 1 is no longer needed.

**Comment by ndhanh96** [comment]
> @ndhanh96 Please try the version attached at #15. Changing to channel 1 is no longer needed.

yeah i was able to use this but don't have fancy feature like your images, still a win though, gps works.
![Screen Shot 2020-08-05 at 13 42 02](https://user-images.githubusercontent.com/8610547/89395280-50621600-d737-11ea-98a6-b366b5ab85a9.png)

**Comment by usr-sse2** [comment]
What do you mean? To show IP address, RSSI, BSSID etc. Option-click the Wi-Fi icon.

**Comment by ndhanh96** [comment]
you should mark this as solved.
