### ISSUE TITLE
RSSI incorrect for 9560

### ISSUE THREAD

**Issue by cowpod** [usr-sse2/Black80211-Catalina#17]
Network is shown as full strength, but after connection the RSSI is -256. 
[previous/irrelevant: connecting to a repeater sometimes shows both networks, one super weak and one "full strength"]
Tried fix-scan.zip from #15, and latest scan commit; it pops up faster, but still same issue.

MacOS 10.15.6
Intel Wireless 9560
usr-sse2/itlwm, Black80211

![Screen Shot 2020-08-04 at 11 30 58 AM](https://user-images.githubusercontent.com/6283258/89348095-b3747f80-d647-11ea-8ea0-7891674f3489.jpg)

[connect.txt](https://github.com/usr-sse2/Black80211-Catalina/files/5024764/connect.txt)

Edited (a lot) for accuracy

**Comment by DashLt** [comment]
Same issue, same hardware, same OS, but not on a repeated network. I turned the wifi on and off a few times to see if it persisted, so that's what the log.txt attached reflects.
[log.txt](https://github.com/usr-sse2/Black80211-Catalina/files/5031595/log.txt)

**Comment by cowpod** [comment]
I believe it's because this is a 2nd gen device; if we managed to patch itlwmx, then the RSSI would possibly be fixed.

**Comment by cowpod** [comment]
Tried with an 8260, it works fine.

**Comment by 1Revenger1** [comment]
My guess is that itlwm::getRSSI() needs to be changed to
```
int itlwm::getRSSI() {
  struct ieee80211_node *bss = com.sc_ic.ic_bss;
  return bss->ni_rssi
}
```

ni_rssi is what is returned to HeliPort, and that is accurate. I can't get Black80211 to start though.

**Comment by rdmitry0911** [comment]
> My guess is that itlwm::getRSSI() needs to be changed to:
> 
> ```
> int itlwm::getRSSI() {
>   struct ieee80211_node *bss = com.sc_ic.ic_bss;
>   return bss->ni_rssi
> }
> ```
> 
> ni_rssi is what is returned to HeliPort, and that is accurate. I can't get Black80211 to start though to test.

I can confirm that this patch solves the issue on the same hardware.

**Comment by MlSAGl** [comment]
> ni_rssi is what is returned to HeliPort, and that is accurate. I can't get Black80211 to start though to test.

I can confirm, it works just fine using my AC-9560

![Capture_d’écran_2020-08-07_à_16_42_31](https://user-images.githubusercontent.com/17383221/89657423-5853be80-d8cd-11ea-9829-80b5fa34ae14.png)

**Comment by cowpod** [comment]
same here; can we get someone with a 8560 to test to make sure nothing broke?
(i'll be able to test again within a few days)

**Comment by usr-sse2** [comment]
Still works on 8265, merged to master.
