### ISSUE TITLE
macOS Big Sur support

### ISSUE THREAD

**Issue by RGarrido03** [usr-sse2/Black80211-Catalina#18]
Hi! I think this project is the cherry on top of the cake. Meanwhile, it only supports macOS Catalina (due to the fact that Apple80211 changes in every major version of macOS). However, are you planning to reverse-engineer and support macOS Bug Sur? I can help testing whatever you want.
I’m using an Intel AX200, so first I’ll have to wait until Black80211 is ported to itlwmx.
Thanks for all your efforts!

**Comment by 1Revenger1** [comment]
IO80211Family has changed quite a bit it seems, and still is changing with every beta. I took a look and a lot of extra classes were added and some new method definitions. It'll likely wait until Big Sur is released or close to it, unless the author of this kext wants to go figure out what changed between betas.

**Comment by usr-sse2** [comment]
I'm planning, but I hadn't yet got time even to install Big Sur.

**Comment by usr-sse2** [comment]
Use alpha3.
