### ISSUE TITLE
Can't build itlwm

### ISSUE THREAD

**Issue by 1Revenger1** [usr-sse2/Black80211-Catalina#20]
Issues aren't enabled over there, so hopefully this is fine.

I can't build itlwm without errors due to FwBinary.cpp. It gives me errors with a few lines, specifically...
```cpp
const unsigned char *[] = {};
const long int *size = sizeof(*);

{IWL_FW("*", *, *_size)};
```
I for some reason can't remove these lines, as FwBinary will revert back to it's original state whenever I build. The most I can do is remove the file from the itlwm target and instead put fwNumber and FwDesc in another header. This builds fine and loads fine, but for some reason whenever Black80211 tries to attach, it errors out when calling `createInterface`. Here is the log: [black80211.txt](https://github.com/usr-sse2/Black80211-Catalina/files/5037402/black80211.txt)

The latest built artifact (and my local copy) also has linking errors on getPHYMode and getFirmwareVersion in itlwm.kext. I had to set them = 0 in Interop.hpp in order to get itlwm.kext to load.

**Comment by usr-sse2** [comment]
FwBinary is autogenerated from firmware files by `fwgen` build target. I didn't change anything there.
Of course, without the firmware nothing will work. CreateInterface fails because before the firmware is loaded the MAC address can't be retrieved.

**Comment by usr-sse2** [comment]
I forgot to push some changes in itlwm but pushed Black80211. I published a new binary release.

**Comment by 1Revenger1** [comment]
ah, that'd be why the file reverts then, and also explains other issues. Makes sense.

Running fwgen just leaves the file empty though for me. If I pull itlwm from openintelwireless, the file is filled once I run fwgen, so I do wonder what is going on there.

**Comment by 1Revenger1** [comment]
Oh, figured it out. If the repo is buried somewhere where a folder has a space, then it breaks the script. Oops.
