### ISSUE TITLE
How to properly uninstall?

### ISSUE THREAD

**Issue by the-eric-kwok** [usr-sse2/Black80211-Catalina#30]
I install this kext with replace OpenCore.efi, install black80211.kext and replace itlwm.kext. This kext works fine, but I do want to uninstall it and switch back to HeliPort. 

After install, I did `defaults write com.apple.NetworkBrowser BrowseAllInterfaces 1` mentioned in #22 

For uninstalling, I switch back to original OpenCore.efi and itlwm.kext. 
And after uninstall, I did `defaults write com.apple.NetworkBrowser BrowseAllInterfaces 0` to revert it.

Now the Airdrop sidebar is gone, but there is always an unusable WiFi icon in my status bar like
![image](https://user-images.githubusercontent.com/16463312/90275423-dea36e00-de94-11ea-9827-4be97e21e09c.png)
(The left one is HeliPort to be clear)

How can I get rid of it?

**Comment by naveenkrdy** [comment]
just hold cmd key and use mouse to click-n-hold on that wifi icon and drag it downwards on desktop and that should remove it.

**Comment by the-eric-kwok** [comment]
> just hold cmd key and use mouse to click-n-hold on that wifi icon and drag it downwards on desktop and that should remove it.

It works! Thanks!
