### ISSUE TITLE
it makes intelbluetooth not work in big sur beta6（xiaomi air 13.3 6200U）

### ISSUE THREAD

**Issue by wxyttty** [usr-sse2/Black80211-Catalina#40]

**Comment by tommyvct** [comment]
Try load `itlwm` first?

Also don't even try to put the kext into /L/E or /S/L/E, It will cause more weird problem. 

If you did mess with /L/E or /S/L/E, please make sure you rebuild the kext cache(`sudo kextcache -I /`) after whatever you did. 

https://github.com/OpenIntelWireless/IntelBluetoothFirmware/issues/177

**Comment by wxyttty** [comment]
put it into /EFI/OC/kext.delete black80211,itlwm and using zxystd's itlwm is ok
