### ISSUE TITLE
Can’t build kext

### ISSUE THREAD

**Issue by Silfalion** [usr-sse2/Black80211-Catalina#5]
Hello, thanks so much for this project. I’m unable to build the kext from xcode, would you have a ready to use kext please?

The error is:

`‘apple80211/high_sierra/IO80211Controller.h’ file not found`

In apple80211.h.

**Comment by usr-sse2** [comment]
You should have selected Catalina target in Xcode, not High Sierra.
Now I've removed the obsolete targets and released the binaries.
